const Info = [{
    "login": "oanapaun91",
    "id": 99691338,
    "node_id": "U_kgDOBfErSg",
    "avatar_url": "https://avatars.githubusercontent.com/u/99691338?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/oanapaun91",
    "html_url": "https://github.com/oanapaun91",
    "followers_url": "https://api.github.com/users/oanapaun91/followers",
    "following_url": "https://api.github.com/users/oanapaun91/following{/other_user}",
    "gists_url": "https://api.github.com/users/oanapaun91/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/oanapaun91/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/oanapaun91/subscriptions",
    "organizations_url": "https://api.github.com/users/oanapaun91/orgs",
    "repos_url": "https://api.github.com/users/oanapaun91/repos",
    "events_url": "https://api.github.com/users/oanapaun91/events{/privacy}",
    "received_events_url": "https://api.github.com/users/oanapaun91/received_events",
    "type": "User",
    "site_admin": false,
    "name": null,
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 1,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "created_at": "2022-02-14T21:16:48Z",
    "updated_at": "2022-05-24T19:19:50Z"
}
]
export default Info;